export enum ActionType {
  FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS',
  FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR',
  ADD_TASKS_SUCCESS = 'ADD_TASKS_SUCCESS',
  ADD_TASKS_ERROR = 'ADD_TASKS_ERROR',
  DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS',
  DELETE_TASKS_ERROR = 'DELETE_TASKS_ERROR',
  UPDATE_TASKS_SUCCESS = 'UPDATE_TASKS_SUCCESS',
  UPDATE_TASKS_ERROR = 'UPDATE_TASKS_ERROR',
}
